services:
  pointcept-env:
    container_name: pointcept-env
    build:
      context: .
      dockerfile: DockerfileEnv
    volumes:
      - /data/sdd/qh:/data
      - ./:/usr/app
      - ${SSH_AUTH_SOCK:-/dev/null}:/ssh-agent
    ports:
      - "4000:80"
    command: tail -f /dev/null
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - INSIDE_POINTCEPT_DOCKER=true
    stdin_open: true
    tty: true

  pointcept-builder:
    container_name: pointcept-builder
    build:
      context: .
      dockerfile: DockerfileBuild
    environment:
      - INSIDE_POINTCEPT_DOCKER=true
    command: tail -f /dev/null
